// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/about.tsx";
import * as $4 from "./routes/archives.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/posts/[name].tsx";
import * as $7 from "./routes/posts/_middleware.ts";
import * as $8 from "./routes/tags.tsx";
import * as $9 from "./routes/tags/[name].tsx";
import * as $$0 from "./islands/ChangeLng.tsx";
import * as $$1 from "./islands/GoBack.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/about.tsx": $3,
    "./routes/archives.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/posts/[name].tsx": $6,
    "./routes/posts/_middleware.ts": $7,
    "./routes/tags.tsx": $8,
    "./routes/tags/[name].tsx": $9,
  },
  islands: {
    "./islands/ChangeLng.tsx": $$0,
    "./islands/GoBack.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
