// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/posts/[name].tsx";
import * as $3 from "./routes/posts/_middleware.ts";
import * as $4 from "./routes/tags/[name].tsx";
import * as $$0 from "./islands/ChangeLng.tsx";
import * as $$1 from "./islands/GoBack.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/index.tsx": $1,
    "./routes/posts/[name].tsx": $2,
    "./routes/posts/_middleware.ts": $3,
    "./routes/tags/[name].tsx": $4,
  },
  islands: {
    "./islands/ChangeLng.tsx": $$0,
    "./islands/GoBack.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
